### ISSUE TITLE
can't login on poggit

### ISSUE THREAD

**Issue by r3pt1s** [poggit/support#102]
![image](https://user-images.githubusercontent.com/54471820/167266737-6e46a6d5-1634-4ef7-a1b2-d7c17b5f9732.png)

how to fix this?????

**Comment by JaxkDev** [comment]
This may be a case of your github being renamed to a previously used name by a different github user ?
cc @SOF3

**Comment by r3pt1s** [comment]
idk, but I renamed my GitHub account months ago, the display name was r3pt1s but the username was not yet and I changed that months ago and changed my username from xXMcpeGamerXx03 to r3pt1s.

**Comment by SOF3** [comment]
resolved
