### ISSUE TITLE
Poggit CI | PHPStan Error

### ISSUE THREAD

**Issue by tobiaskirchmaier** [poggit/support#104]
Hello, can anyone help me with this?
```

PHPStan Error

An error occurred while running PHPStan

PHPStan failed with ID 'phpstan-7459-fa4722b0', contact support with the ID for help if this persists.

```
Locally, PHPStan works without any problems.

**Comment by Tobias-2006** [comment]
The plugin has a `src-namespace-prefix`.
Virions should end up in directory ´src/libs/.../´ but they end up in `src/{src-namespace-prefix}/libs/.../`.

**Comment by Endermanbugzjfc** [comment]
I use a GitHub workflow to convert the namespace-prefixed project to PSR-0 and make Poggit build the converted branch.

**Comment by Endermanbugzjfc** [comment]
The workflow is available on my Gist, please find it yourself.

**Comment by JaxkDev** [comment]
This should have been fixed a while ago, please re-open if it persists on the main repo at https://github.com/poggit/poggit/issues
