### ISSUE TITLE
Poggit PMMP Errors

### ISSUE THREAD

**Issue by Xgamer6** [poggit/support#110]
I would create a Plugin that have a command and when the command executed a message will be send to a user!
My Code: https://github.com/Xgamer6/CommandX/tree/main/

And you can check errors at Dev Build #22
https://poggit.pmmp.io/ci/Xgamer6/CommandX/CommandX/dev:22

It would be good when you check the code for me and fix it!

**Comment by SOF3** [comment]
This is not a plugin dev support forum.
