### ISSUE TITLE
Question regarding releasing a forked plugins

### ISSUE THREAD

**Issue by Thunder33345** [poggit/support#2]
> Do not submit plugins written by other people, unless you have obtained prior explicit permission from them. If you want an updated plugin to be listed on Poggit, request it at the Poggit Orphanage Office.

They arent seems to be more then that regarding releasing a forked version of another plugin
So here's the questions:
1. Is there any guidelines for releasing a forked plugin without author's permission? since it's a open source community anyways, if someone want to revieve dead projects shouldnt they be able to do so?
1. How many amount of change would make the plugin no-longer considered as plagiarism thus should be considered to allowed to be released
1. Is there any guidelines for if one individual wished to release a forked plugin should consider before releasing
1. Currently we fork the plugins who been requested to be released to poggit using poggit orphanage, but what if it's a edited and will be maintained by a fork maintainer should they be allowed to release it under their own name?
1. Why does poggit choose to restrict the release of forked version of plugins, under an open source environment, i understand there concerns about people who would just rename the plugin and forget about it, but there also people who are happy to add brand new features to a un-maintained plugin
1. If I manage a forked version of PureChat [see here](https://github.com/dihydrogen-monoxide/PureChatReloaded/) and wish to release it due to it bringing more flexibility what actions should i take before releasing it?

Most of these questions are raised over the fork of purechat i made, and also to at the very least allow and come up some sort of guideline for forked/edited plugins

**Comment by Awzaw** [comment]
Good questions for which we don't yet have all the answers yet - the current rule is to follow githubs own policy - i.e forks are allowed without permission from the author, as long as it is clear who the original author is, that the original licence is respected, that content is not plagiarized etc. However.... Poggit still reserves the right to refuse any plugin that doesn't add enough functionality (not yet quantified) to the original to be considered a separate plugin, and of course the usual criteria for code quality, readability, etc.

Poggit orphanage is currently only a means to release 'classic' plugins which are currently either unmaintained, or which the author doesn't have time to add to Poggit (or is uncontactable). I think we'll be discussing all this soon in more detail on slack :-)

**Comment by Thunder33345** [comment]
i suppose you meant the new slack, hopefully once that's done i can get my answers

**Comment by SOF3** [comment]
I think we can generalize multiple levels of "forking" plugins:

1. no credits, not fork, almost no code change, name changed, namespace changed (or no need to change if does not contain author name) (obviously unacceptable)
2. no credits, almost no code change, name reserved, released in own name (obviously unacceptable)
3. no credits, but is a fork, almost no code changes
4. given credit in description, is not a fork (may violate licenses such as GPL), almost no code changes
5. given credit in description, is a fork, almost no code changes, no license violations
6. given credit in description, is not a fork, major changes (addition of features, etc.), may violate license
7. given credit in description, is a fork, major changes, no license violations

**Comment by Thunder33345** [comment]
Brings us back to this:
>Do not submit plugins written by other people, unless you have obtained prior explicit permission from them. If you want an updated plugin to be listed on Poggit, request it at the Poggit Orphanage Office.

what if it is a fork clearly stated in description with all credits to author, it also adds substantial code changes and new features, should that be theoretically clear for release in most normal cases?

**Comment by SOF3** [comment]
@Thunder33345 I know it's badly worded, but it at least warns people who do not read enough ;)

**Comment by SOF3** [comment]
With the "authors" entry in the submission form, this issue can be better resolved.
