### ISSUE TITLE
spammmy

### ISSUE THREAD

**Issue by dktapps** [poggit/support#30]

**Comment by jasonwynn10** [comment]
spam by @dktapps what is even happening??

**Comment by dktapps** [comment]
@jasonwynn10 testing an anti-spam bot

**Comment by Thunder33345** [comment]
that sounds cool but it would end up in the timeline or notifications anyways

**Comment by jasonwynn10** [comment]
True, but it would give SOFe and dktapps an easier time closing and labeling the issues as spam

**Comment by dktapps** [comment]
https://github.com/poggit/support/issues/31

**Comment by Thunder33345** [comment]
so there's a blocking too!! nice
