### ISSUE TITLE
Plugin scripts

### ISSUE THREAD

**Issue by jasonwynn10** [poggit/support#39]
Will Poggit support single script plugins? I mean whole plugins within one php file without all the directories and the plugin.yml

**Comment by SOF3** [comment]
According to @shoghicp:
http://forums.pocketmine.net/threads/new-plugin-scripting-format-draft.8335/

> Remember, you can't release the single-file plugin. This is only for fast server scripting by the end-user or prototyping. So "Old API" developers still need to do the same as on normal plugins (syntax is equal) except that you can do everything on a single file.

The same policy for Poggit. Script plugins are not for production use, and there is no reason for Poggit to support it.
