### ISSUE TITLE
Add plugin

### ISSUE THREAD

**Issue by Matthww** [poggit/support#42]
So I tried to add one of my repo's to Poggit. But I can't find where to enable the plugin. If I click on the "Admin" button it says I need to add a plugin first, leading me to the homepage where I can't find the option to add a plugin.

**Comment by SOF3** [comment]
Seems that some internal errors happened with your account.
Could we talk privately on Gitter? Find me on https://gitter.im/SOF3

**Comment by NiekertDev** [comment]
I have the exact same problem as Matthww, I also changed my github name.
