### ISSUE TITLE
@poggit-bot is leaving messages on the gh-pages branch which is not included in the .poggit.yml

### ISSUE THREAD

**Issue by jasonwynn10** [poggit/support#43]
^^
@poggit-bot is leaving annoying messages on branches that are for the website, not the plugin. Is there a way to prevent this?

**Comment by SOF3** [comment]
One possible way is to create a .poggit.yml in gh-pages that declares a "branches" attribute without the gh-pages branch. 
Other attributes will be ignored if the .poggit.yml on the branch being built does not include the branch being built. The .poggit.yml on other branches will not be considered or affected.
