### ISSUE TITLE
Logout every time I leave the page

### ISSUE THREAD

**Issue by jasonwynn10** [poggit/support#44]
I started noticing that recently, poggit logs my github account out when I close the tab. Is there a way to stay logged in?

**Comment by SOF3** [comment]
@Intyre @Awzaw any ideas? I am experiencing the same issue too. Might there be an issue with the PHP docker setup?

**Comment by Awzaw** [comment]
I don't know, but I'm almost certain it started with the move to docker.

**Comment by jasonwynn10** [comment]
Issue resolved 👍

**Comment by Awzaw** [comment]
For reference, the default value for session.cookie_lifetime is 0, hence this issue.

**Comment by SOF3** [comment]
It's 36000 right now. Still too short?

**Comment by Awzaw** [comment]
Probably, yes

**Comment by jasonwynn10** [comment]
@Awzaw agreed
