### ISSUE TITLE
Multiple Versions of the same plugin in review phase

### ISSUE THREAD

**Issue by jasonwynn10** [poggit/support#45]
![screenshot 15](https://user-images.githubusercontent.com/16521025/27267554-436a294c-5477-11e7-9502-413ac81a53cc.png)
I couldn't help but notice that on this screen are two plugins with two postings with different version numbers on each. Are the plugins supposed to do that, or should they replace the previous versions?

Both PlayerInfo and StaffChat have two posts in the review page.

**Comment by SOF3** [comment]
This is in /review, not in /pi, right?

**Comment by SOF3** [comment]
Older versions should also get reviewed so that their changelog gets into the history. However, only reviewing the first one is enough.

I should probably indeed hide them.

**Comment by jasonwynn10** [comment]
![screenshot 25](https://user-images.githubusercontent.com/16521025/27309732-a3914ad8-5523-11e7-9329-1870236dbab4.png)
I found more here on the side. Also I'm not logged in while viewing these.
