### ISSUE TITLE
Poggit direct download link

### ISSUE THREAD

**Issue by McpeBooster** [poggit/support#46]
Is it possible to create a direct download link with Poggit with which you can always download the latest dev build without having to update the link always?

**Comment by TheDiamondYT1** [comment]
As far as i know, the *only* way is to loop through each entry in https://poggit.pmmp.io/releases.json and get the `artifact_url` from the JSON.

Hopefully there will be a more efficient way in the future.

**Comment by McpeBooster** [comment]
The Problem for that is that my Plugins got redricted by Poggit so they arent released...

**Comment by TheDiamondYT1** [comment]
@McpeBooster May i ask which plugin it is that you want to get the download link of?

**Comment by McpeBooster** [comment]
I have my website http://boostcraftpe.de/plugins/ and I would not update with any update I make the link ... Therefore I wanted a self updating link.

**Comment by TheDiamondYT1** [comment]
Well it's possible if its released. I suppose you should check your plugin and submit it again.

###### This issue can now be closed

**Comment by McpeBooster** [comment]
A couple of my plugins were already released and then after a few weeks someone thought: I reject the plugins..

**Comment by TheDiamondYT1** [comment]
Well complain to @SOF3 on the forums 😂

**Comment by Thunder33345** [comment]
lets not go offtopic
i think there it should get the latest download/page/anything by adding a /latest

**Comment by Awzaw** [comment]
@McpeBooster  once you get your releases out on Poggit you can use a link like this: https://poggit.pmmp.io/get/CustomHelp-McpeBooster which will always download the latest release.

@SOF3 explained why at least one was rejected, I'm not sure about the others, and there haven't been updates to those 2 for about a month - I'm curious to know if KnockbackFFA use of SignChangeEvent actually works with MCPE 1.1.

I'm not sure why SOFe rejected PowerNick, I'll ask.

**Comment by McpeBooster** [comment]
Thank you @Awzaw .

Why shouldn't work the "SignChangeEvent" in the 1.1?

**Comment by Awzaw** [comment]
The [changes to SignChangeEvent]([https://github.com/pmmp/PocketMine-MP/issues/956]) means that depending on how you handle the user input, and how you store the sign data, you may get unexpected results.

**Comment by McpeBooster** [comment]
Ok maybe i use an other way to do that

**Comment by SOF3** [comment]
Development builds aren't releases. Before we get a sufficient amount of releases and a self-sustaining plugin reviewing community, I'd rather not have a direct link to development builds to minimize confusion that development builds should be used in production.
