### ISSUE TITLE
'Release' section for virions

### ISSUE THREAD

**Issue by Sandertv** [poggit/support#47]
Currently, virions are not the easiest to browse. You can find them through CI, but without knowing the name of one, it's hard to find out whether there is a virion that serves your needs. Perhaps it is a useful idea to add some kind of release/browse section dedicated to virions only.

I understand this is a lot of work for (seemingly) not too important features, but it really would be a useful feature. No rush either way. It'd be cool if you'd implement this in Poggit.

**Comment by SOF3** [comment]
Virions are only for developers, so an index in the CI is enough.

I remember this duplicates an issue in Poggit/Poggit about downloading viroons conveniently. This issue can be combined with that issue. Please comment there.
