### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Keaton1188** [poggit/support#49]
Hi all, having a issue with getting plugins to work with DevTools, I have edited some plugins so that they will work with ALPHA-7, this didn't used to be an issue and now is.

![untitled](https://user-images.githubusercontent.com/24898745/30210345-33d3d296-9494-11e7-8dba-18e2705d426f.png)

Running PocketMine-MP version 1.6.2dev "Unleashed" (API 3.0.0-ALPHA7)
PE version v1.1.0.55

**Comment by Awzaw** [comment]
Please update to the latest EconomyAPI. The latest 3.0.0-alpha7 builds are [here](https://poggit.pmmp.io/ci/poggit-orphanage/EconomyS/EconomyAPI)

**Comment by Keaton1188** [comment]
Hey @Awzaw, Yea just saw there was an update for it. Tis working fine now.

Was wondering about other plugins that have stopped getting updates. used to change the API version of them myself then upload them back to the server with DevTools, worked fine.

Now it seems something has changed thats stopping me from doing that.

**Comment by Awzaw** [comment]
API version updates reflect changes to the PM source code that _may_ require plugins to update. If the PM changes only concern Entities, for example, then plugins that don't use Entities might work if you just change the API version... but recent improvements to PM, especially in alpha7, affect nearly early every aspect of the API (e.g strict typing) and often require a full overhaul of the code for every plugin. Just changing the API version may have worked fine for years with simple plugins such as /xyz, but recently there have been a massive number of API changes that require a proper update, not just changing the plugin API version to fool PM into loading it. See [here](https://forums.pmmp.io/threads/updating-a-plugin-to-work-with-different-apis-the-manual-way.3647/#post-34991) for a guide to updating plugins correctly.

**Comment by SOF3** [comment]
The correct way for updating plugins should be to actually publicize updated versions of existing plugins, not to teach every person how to update, though.
