### ISSUE TITLE
Block Meta Data - Issue 

### ISSUE THREAD

**Issue by Keaton1188** [poggit/support#50]
Hi all, just went to check on our MCPE server and noticed a lot of spam in the console about Block Meta Data. Any idea?

![untitled](https://user-images.githubusercontent.com/24898745/30403067-e414031e-98d7-11e7-87dc-d06538a539c9.png)

@Awzaw

**Comment by SOF3** [comment]
Poggit Support is only intended for issues related to Poggit. For plugin help, please use the forums: https://forums.pmmp.io/forums/plugin-help
Also make sure you are using the latest PMMP version.
