### ISSUE TITLE
Pocketmine Won't Update

### ISSUE THREAD

**Issue by FrontlineMist57** [poggit/support#51]
My pocketmine server is running MCPE version 0.15.0.0. Current minecraft is running MC 1.15.0
is there any way to update this?

   -Thanks... Front

`<version>                                                                                    implementing API version 2.0.0 for Minecraft: PE v0.15.0.0 alpha (protocol version 81)ng PocketMine-MP 1.6dev-# ã[REDACTED]ã`

**Comment by SOF3** [comment]
Where are you downloading from?...
