### ISSUE TITLE
Plugin can not be uploaded.

### ISSUE THREAD

**Issue by GamakCZ** [poggit/support#52]
![500 internal server error - google chrome 22 10 2017 10_40_29](https://user-images.githubusercontent.com/17053298/31860111-9b140900-b715-11e7-9afb-3d8fd9e22e2b.png)

**Comment by GamakCZ** [comment]
I tried to unsubscribe and log in again, but the error is the same

**Comment by SOF3** [comment]
https://github.com/CzechPMDevs/BuilderTools/blob/eff49432b76792893f3362bb59a00213fe6036d2/.poggit.yml#L7
Why did you write that line?

**Comment by SOF3** [comment]
Fixed in poggit/poggit@190f4a3
