### ISSUE TITLE
Please remove the TBNRItzDoge/Commissions repository from poggit

### ISSUE THREAD

**Issue by jasonwynn10** [poggit/support#55]
UniverseCreations/Commissions is a copyrighted repository. Please remove it from poggit

**Comment by Awzaw** [comment]
I can't find any poggit repos by TBNRItzDoge or UniverseCreations - can you post a link?

**Comment by Thunder33345** [comment]
https://github.com/TBNRItzDoge/Commissions
but poggit https://poggit.pmmp.io/ci/TBNRItzDoge/Commissions was not found
just asking for confirmation, shouldnt it be automatically removed/hidden from public view when the repository is not found?(ex dmca takedown)

**Comment by Awzaw** [comment]
Yes, the resource isn't automatically deleted from disk, but if a repo is removed from github the plugins build page won't be accessible. Unless sof3 already deleted it, I'd say TBNRItzDoge tried to enable it on Poggit (his repo does have .poggit.yml) and it failed, or he disabled it himself already.

**Comment by jasonwynn10** [comment]
Okay. All is well as long as the plugins within the repository are not available on poggit. Thank you for the support
