### ISSUE TITLE
The repo kenygamer/ChatLogger does not have Poggit CI enabled.

### ISSUE THREAD

**Issue by kenygamer** [poggit/support#56]
I can't disable Poggit CI for my repo and re-enable it (something went wrong).
The repo kenygamer/ChatLogger does not have Poggit CI enabled.

**Comment by Awzaw** [comment]
Is this for the project https://poggit.pmmp.io/ci/TheFixerDevelopment/pmmp-plugins/ChatLogger?

**Comment by kenygamer** [comment]
That is a fork of my repository. I'm talking about https://github.com/kenygamer/ChatLogger

**Comment by kenygamer** [comment]
I can't disable Poggit CI for ServerRules, Coords, KillMoney and ChatLogger. I will re-enable them later.
