### ISSUE TITLE
Possible PQRS addition: Check if plugin is enabled in plugin commands

### ISSUE THREAD

**Issue by SalmonDE** [poggit/support#58]
Commands registered by plugins can still be ran by players if the plugin was disabled.

Similar to what the PQRS says about checking whether the plugin is still enabled on completion of an async task, I suggest adding a clause for checking if the plugin is enabled when a plugin command is run IF necessary. (Not all of the plugin commands are affected.)

I've posted a test plugin with the mentioned behaviour in [a forum discussion](https://forums.pmmp.io/threads/pqrs-addition-check-if-plugin-is-enabled-in-execute.5404/).

**Comment by SOF3** [comment]
I believe this is a problem to be handled from PocketMine: the plugin commands are not completely unregistered.

**Comment by SalmonDE** [comment]
I see. I'll go on and close this then.

**Comment by SOF3** [comment]
See if you want to create an issue on pmmp/PocketMine-MP
