### ISSUE TITLE
About notation when using virion

### ISSUE THREAD

**Issue by fuyutsuki** [poggit/support#60]
I hope to display not only the version of virion but also the branch name.
like this (example branch name is "hotfix-1.2.13")
![default](https://user-images.githubusercontent.com/16377174/38326811-be43cae4-3881-11e8-8e58-b6945e41045d.png)

**Comment by SOF3** [comment]
Next time please create suggestions in the https://github.com/poggit/poggit repo.

**Comment by fuyutsuki** [comment]
Oops, sorry.

**Comment by SOF3** [comment]
![image](https://user-images.githubusercontent.com/19623715/38354552-9c308968-38ec-11e8-8f46-566221266b65.png)

**Comment by fuyutsuki** [comment]
Thanks.
