### ISSUE TITLE
poggit-ci is not working

### ISSUE THREAD

**Issue by djdisodo** [poggit/support#61]
![ddsfa](https://user-images.githubusercontent.com/17721656/42504424-b4cedc9c-8476-11e8-877c-1ec24e0481d6.PNG)

github was not worked for few times
(it's fixed now)
but poggit-ci still not working

**Comment by SOF3** [comment]
Which repo>

**Comment by SOF3** [comment]
https://poggit.pmmp.io/ci/recent Poggit is still working for new builds. There must be a particular issue with your repo. I don't see any errors in the error log. Can you link?

**Comment by djdisodo** [comment]
https://github.com/MiniGameAPI-PM/MGARace

**Comment by SOF3** [comment]
@poggit-bot has sent comments in your commits explaining why the build failed. Have you read them?
