### ISSUE TITLE
Quota?

### ISSUE THREAD

**Issue by AlexPads** [poggit/support#62]
This is the message that i have gotten on my recent commits.
I am Helping imwood04 start out as a dev i have started using the github for desktop client as to not produce as many commits to fix a single issue!

Message:

Dear Poggit user,

This is an automatic message from Poggit-CI. Poggit-CI was triggered by this commit, but failed to create builds due to the following error:

Resend this delivery later. This commit is triggered by user AlexPads, who
has created 50 Poggit-CI builds in the past 168 hours.

Contact @SOF3 [on Discord](https://discord.gg/NgHf9jt) to request for extra
quota. We will increase your quota for free if you are really contributing
to open-source plugins actively without abusing Git commits.
As a result, no builds could be created from this commit. More details might be available for repo admins at the webhook delivery response log — see the webhook starting with https://poggit.pmmp.io/webhooks.gh.repo and look for the delivery with ID 69283758-c0f2-11e8-9dbd-f514de783e4d.

Shall you need any assistance, you may contact us on on Discord, or more publicly, on GitHub. Commenting on this commit directly will not notify any Poggit staff.

Regards,
Poggit Bot (@poggit-bot)
The official Poggit automation account

Thanks for understanding even if you don't :) Love u guys!

**Comment by SOF3** [comment]
We will not reset your quota because most of your commits are unnecessary. We will only increase quota for people who contribute many commits.
