### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by ghost** [poggit/support#65]
I was gonna submit my plugin but I got this message saying

400 Bad Request
  
Cannot find the project  from the .poggit.yml back then. Was the project renamed? Please contact a Poggit admin if you need help.
Is there a way to fix this

**Comment by SOF3** [comment]
What are you trying to do?

**Comment by WEATHERCRAFTYT1** [comment]
Submit a plugin

**Comment by SOF3** [comment]
which plugin, and which build?
