### ISSUE TITLE
Can't download my plugin

### ISSUE THREAD

**Issue by Minecraftfan714** [poggit/support#69]
![image](https://user-images.githubusercontent.com/50752658/63692416-e5634c00-c811-11e9-9f43-c390d72f35b4.png)

I can't download my plugin :(

**Comment by Minecraftfan714** [comment]
1:
![image](https://user-images.githubusercontent.com/50752658/63693273-ef864a00-c813-11e9-8c01-73bd5dd11558.png)

2:
![image](https://user-images.githubusercontent.com/50752658/63693249-d8475c80-c813-11e9-869e-55a44f80b876.png)
![](https://user-images.githubusercontent.com/50752658/63692416-e5634c00-c811-11e9-9f43-c390d72f35b4.png)

**Comment by SOF3** [comment]
Link to repo?

**Comment by SOF3** [comment]
Due to the special nature of private repos, we generally do not support them.

**Comment by SOF3** [comment]
I mean, you can still use Poggit with them, but we are unable to help with such problems.
