### ISSUE TITLE
Can't download my Plugin, why?

### ISSUE THREAD

**Issue by Minecraftfan714** [poggit/support#70]
Hey, I can't download my Plugin. First I created .poggit and went to that link:

![image](https://user-images.githubusercontent.com/50752658/64075854-960f9680-ccbd-11e9-9930-fb1fbb1382c6.png)
ThenI klicked download:

![image](https://user-images.githubusercontent.com/50752658/64075859-b0497480-ccbd-11e9-84fc-7e30e11c26c2.png)
Then OK

![image](https://user-images.githubusercontent.com/50752658/64075866-d40cba80-ccbd-11e9-921d-41002b88b50d.png)
"This poggit.pmmp.io-site wasn't found"

![image](https://user-images.githubusercontent.com/50752658/64075877-f3a3e300-ccbd-11e9-9599-a3d1542c378a.png)
What have I done wrong? 

PS: excuse my english, I'm Swiss

**Comment by SOF3** [comment]
As stated before, private repositories are not supported here because we don't have access to debug the issue for you.

**Comment by Minecraftfan714** [comment]
> As stated before, private repositories are not supported here because we don't have access to debug the issue for you.

Where can I ask questions or write if I have a problem?

**Comment by SOF3** [comment]
We can't see your private repos, so there is no way we can help.
