### ISSUE TITLE
How to "provide a Github access token"?

### ISSUE THREAD

**Issue by Minecraftfan714** [poggit/support#71]
Hey,

There is an error:

> This is a private repo. You must provide a GitHub access token if you download this plugin without browser (e.g. through curl or wget).

What to do ?

![image](https://user-images.githubusercontent.com/50752658/64283826-7c3db000-cf58-11e9-98d9-ba7ccf96e067.png)

(I tried to download my plugin)
PS: excuse my english, I am Swiss

**Comment by SOF3** [comment]
Curl: `-H "Authorization: bearer $TOKEN"` where $TOKEN is an access token generated from https://GitHub.com/settings/tokens
