### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by XGDavid** [poggit/support#76]
400 Bad Request Cannot find the project AdminsList from the .poggit.yml back then. Was the project renamed? Please contact a Poggit admin if you need help. 
Plugin Name: AdminsList

**Comment by SOF3** [comment]
Please provide more details.

**Comment by XGDavid** [comment]
i want to release the plugin.. and give me this error.....

**Comment by XGDavid** [comment]
pfffff, I accidentally closed ....

**Comment by SOF3** [comment]
> Please provide more details.

**Comment by XGDavid** [comment]
this plugin is private, thx for help. Good day
