### ISSUE TITLE
Sanitized project name, from "0" to "0"

### ISSUE THREAD

**Issue by radledazzler13** [poggit/support#78]
How do I fix the error: Sanitized project name, from "0" to "0"

**Comment by SOF3** [comment]
Check your `.poggit.yml`. You most likely set an incorrect format. Look at other repos to see how it should be set up.

**Comment by SOF3** [comment]
https://github.com/radledazzler13/RadPlugins It seems your plugin is not in correct format. The `Main.php` file should not be placed next to `plugin.yml`, but in a source folder under PSR-0 structure.

**Comment by radledazzler13** [comment]
How do I move the Main.php file?

**Comment by radledazzler13** [comment]
I’m sorry I just started doing this yesterday.

**Comment by SOF3** [comment]
This is not a plugin development or GitHub usage support line.
