### ISSUE TITLE
Can’t add a repo

### ISSUE THREAD

**Issue by WEATHERCRAFTYT1** [poggit/support#79]
I’m trying to add a repo to dev builds but it isn’t working. I get the poggit.ci on the GitHub but not on poggit. I get this message.

You may want to create a commit in your repo that modifies anything in .poggit.yml (for example, add an extra line feed somewhere) to trigger the first build.

I don’t know what this means or how to to fix it

**Comment by SOF3** [comment]
Please provide full steps what you have done. In particular, please provide link to your repository.

**Comment by WEATHERCRAFTYT1** [comment]
ook https://github.com/WEATHERCRAFTYT1/BuildBattle

When i finshed the plugin I added a repo thats when i error happned

**Comment by SOF3** [comment]
You may want to create a commit in your repo that modifies anything in .poggit.yml (for example, add an extra line feed somewhere) to trigger the first build.

**Comment by WEATHERCRAFTYT1** [comment]
Wdym by this is what idk understand

**Comment by SOF3** [comment]
it means exactly what it says.

**Comment by WEATHERCRAFTYT1** [comment]
😦😦😦😦😦😦
I’m not sure but kk
