### ISSUE TITLE
The repo is not accessible to your GitHub account (@kenygamer)

### ISSUE THREAD

**Issue by kenygamer** [poggit/support#80]
I was submitting some plugins to Poggit. I first tried submitting the plugins from private repo (forgot to change visibility) and now that they are public, I could successfully upload two but I got stuck with MineSell.

Error:
```
The repo kenygamer/MineSell does not exist or is not accessible to your GitHub account (@kenygamer).
```

When I try to go to my projects, I get a `500 Internal Server Error`. Reference ID: `bf05-5fc7318976d9752b-AMS`

**Comment by SOF3** [comment]
Closed as stale
