### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by OguzhanUmutlu** [poggit/support#87]
https://poggit.pmmp.io/p/TntTag/1.0.3 and https://poggit.pmmp.io/p/BlockHunt/1.0.3 approved but 1.0.2s are featured so they are no longer in featured list can they fix it

**Comment by SOF3** [comment]
@jasonwynnn10 do we expect them to continue to be featured?

**Comment by OguzhanUmutlu** [comment]
> @jasonwynn10 do we expect them to continue to be featured?

why not?

**Comment by OguzhanUmutlu** [comment]
@SOF3

**Comment by SOF3** [comment]
Closed as stale.
