### ISSUE TITLE
Adverse possession on a plugin.

### ISSUE THREAD

**Issue by Vecnavium** [poggit/support#91]
The plugin NaviCompass https://github.com/Xenophilicy/NaviCompass has not been updated for several months now.
I was not able to create an issue or a PR as the author has disabled this on their repo. They have also stated they are no longer updating their plugin and they have froze it. The author has also mentioned this on their plugin page on Poggit. https://poggit.pmmp.io/p/NaviCompass/2.3.3

I would like to maintain this to update it to the latest version and it properly working. And maintain it for the long-term including API 4.0.0.

**Comment by Vecnavium** [comment]
Now that's handled and the plugin's updated, how will submissions work to submitting the latest version?

**Comment by SOF3** [comment]
If you're a collaborator, you should be able to submit updates directly.
