### ISSUE TITLE
Adverse possession on a plugin

### ISSUE THREAD

**Issue by Vecnavium** [poggit/support#92]
The plugin Slapper https://github.com/jojoe77777/Slapper as we all know the author Jojoe77777 is inactive overall and not just the Slapper plugin, and I would like to step up and officially take over and maintain it for the long run both API 3.0.0 and API 4.0.0 and future APIs.

There has been **many** issues created by several people about the plugin being out of date and PRs has been created by others while it has been untouched by Jojoe77777 on both issues and PRs.

**Comment by Vecnavium** [comment]
The 7 days mark has passed and nothing has happened on the Slapper PR.

**Comment by SOF3** [comment]
Since @jojoe77777 is not responding, this adverse possession shall commence to the next phase. @Vecnavium please enable Poggit for your fork, and I will relink the Slapper release to your project.

**Comment by Vecnavium** [comment]
I have enabled it.

**Comment by SOF3** [comment]
Transfer complete.
