### ISSUE TITLE
Cannot enable Poggit-CI

### ISSUE THREAD

**Issue by keenanyafiqy** [poggit/support#94]
I can't enable Poggit-CI
It's just "Building repo" and then when I refresh
It doesn't turned on
What should I do?

**Comment by SOF3** [comment]
![](https://cdn.discordapp.com/attachments/336165105689690122/897872115104120892/tanjirules.png)

It is working for everyone else, so if it doesn't work for you, it is your specific problem, so you should provide specific information.

**Comment by SOF3** [comment]
Please provide more information.
