### ISSUE TITLE
Adverse Possession of SimpleWarp

### ISSUE THREAD

**Issue by TheDataLion** [poggit/support#95]
I hereby request the adverse possession of the following plugin: SimpleWarp

https://poggit.pmmp.io/p/SimpleWarp

The aforementioned plugin is eligible for adverse possession because:

- It is not compatible with the latest stable PocketMine-MP API 4.0.0 as released on 3.0.0, which is more than 14 days ago.

I have offered to help update the plugin to resolve all the issues above in the pull request https://github.com/falkirks/SimpleWarp/pull/73 , but there have not been any response from the maintainers with regard to the pull request. As a result, I am requesting to take over the control of this release line.

I hereby notify the previous contributors of this adverse possession request:

- @falkirks
- @joshnorth
- @SOF3 

If no valid objection is received within 7 days, the permission to release updates for SimpleWarp will be permanently and irreversibly transferred to me.

**Comment by falkirks** [comment]
I still maintain this repository. The PR you made is like 3 hours old. I'll review and merge it.

For my plugins I usually go through a process where you make a PR or two and then I'll add you to the repository and the page poggit page. Next time if you need me just like email me at hi@noa.dev.

**Comment by TheDataLion** [comment]
I'm sorry,
I was assuming since the plugin hasn't been updated in 3 years it was abandoned.

**Comment by dktapps** [comment]
It hasn't been updated for 3 years because it didn't need to be, because the API was frozen since June 2018 ...

**Comment by SOF3** [comment]
Since there's some confusion, let me clarify: adverse possession requests only start getting processed 7 days after the initial PR was created, and only get approved ,7 ays after the start of processing. I will add this to the issue template to avoid confusion in the future.
