### ISSUE TITLE
Adverse Possession of AutoClearLagg

### ISSUE THREAD

**Issue by NhanAZ** [poggit/support#96]
I hereby request the adverse possession of the following plugin:

https://poggit.pmmp.io/p/AutoClearLagg

The aforementioned plugin is eligible for adverse possession because:

- [x] It is not compatible with the latest stable PocketMine-MP API 4.0.0 as released on 3.0.0, which is more than 14 days ago.

I was not able to create an issue or a PR as the author has disabled this on their repo.

I hereby notify the previous contributors of this adverse possession request:

- @TwistedAsylumMC
- @iiFlamiinBlaze
- @HyperFlareMC
- @JoshuaPHYT

If no valid objection is received within 7 days, the permission to release updates for AutoClearLagg will be permanently and irreversibly transferred to me.

**Comment by NhanAZ** [comment]
It's been 7 days and there are no valid objections from the author or contributors of the AutoClearLagg plugin

**Comment by JaxkDev** [comment]
There allowed a 14 day period to update to PM4 its only been 11 days since release so technically its not eligible yet.

**Comment by SOF3** [comment]
>  It is not compatible with the latest stable PocketMine-MP API 4.0.0 as released on 3.0.0, which is more than 14 days ago.

This is not true at all...

**Comment by NhanAZ** [comment]
I think the [ClearLag](https://poggit.pmmp.io/p/ClearLag/1.0.0) plugin will replace this plugin, so I'm closing this issues. Regards!
