### ISSUE TITLE
I can't remove my plugin from Poggit

### ISSUE THREAD

**Issue by NhanAZ** [poggit/support#97]
### Issue description
I want to remove my plugin from poggit because of some problem.
But I can't find the delete button in the release edit

https://github.com/NhanAZ/Images/blob/master/hmm.png

### Other information
- Link to plugin: https://poggit.pmmp.io/p/KeepItems/1.0.0

**Comment by SOF3** [comment]
The image isn't loading for me.

**Comment by xAliTura01** [comment]
If it doesn't load, right click and click **Open in new tab.**

**Comment by NhanAZ** [comment]
> The image isn't loading for me.

Sr. I fixed the link to the image!

**Comment by SOF3** [comment]
> ### Issue description
> 
> I want to remove my plugin from poggit because of some problem. But I can't find the delete button in the release edit
> 
> https://github.com/NhanAZ/Images/blob/master/hmm.png
> ### Other information
> 
>     * Link to plugin: https://poggit.pmmp.io/p/KeepItems/1.0.0

The plugin has already been approved. Are you sure you want to reset it to draft? What is the reason?

**Comment by NhanAZ** [comment]
I definitely want to turn it into a draft.
Reason: I have been given ownership of the [KeepInventory](https://poggit.pmmp.io/p/KeepInventory/1.0) plugin so I will develop the KeepInventory plugin instead of KeepItems plugin

**Comment by SOF3** [comment]
Done.
